# Generated by Django 4.1 on 2022-08-07 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='title',
            field=models.TextField(default='title', max_length=200),
            preserve_default=False,
        ),
    ]
