# Generated by Django 4.1 on 2022-08-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_photo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.TextField(default='title', max_length=200),
        ),
    ]
